#include "ScriptEnum.h"
#include "OrderID.h"
#include <BWAPI.h>

typedef struct __unitInfo
{
  const char  *pszScriptUnitName;
  int         iComputerIdleOrder;
  int         iComputerInternal;
} unitInfo;

unitInfo pszUnitInfo[] =
{
  { "marine",                      OrderID::Guard, 0 },
  { "ghost",                       OrderID::Guard, 0 },
  { "vulture",                     OrderID::Guard, 0 },
  { "goliath",                     OrderID::Guard, 0 },
  { "", 0, 3 },
  { "siege_tank",                  OrderID::Guard, 0 },
  { "", 0, 3 },
  { "scv",                         OrderID::Guard, 3 },
  { "wraith",                      OrderID::Guard, 0 },
  { "science_vessel",              OrderID::Guard, 0 },
  { "gui_montag",                  OrderID::Guard, 3 },
  { "dropship",                    OrderID::PickupIdle, 0 },
  { "battlecruiser",               OrderID::Guard, 0 },
  { "spider_mine",                 OrderID::VultureMine, 3 },
  { "nuke",                        OrderID::Nothing, 3 },
  { "civilian",                    OrderID::Guard, 3 },
  { "sarah_kerrigan",              OrderID::Guard, 3 },
  { "alan_schezar",                OrderID::Guard, 3 },
  { "alan_turret",                 OrderID::TurretGuard, 3 },
  { "jim_raynor_vulture",          OrderID::Guard, 3 },
  { "jim_raynor_marine",           OrderID::Guard, 3 },
  { "tom_kazansky",                OrderID::Guard, 3 },
  { "magellan",                    OrderID::Guard, 3 },
  { "edmund_duke",                 OrderID::Guard, 3 },
  { "", 0, 3 },
  { "edmund_duke_sieged",          OrderID::Guard, 3 },
  { "", 0, 3 },
  { "arcturus_mengsk",             OrderID::Guard, 3 },
  { "hyperion",                    OrderID::Guard, 3 },
  { "norad_2",                     OrderID::Guard, 3 },
  { "siege_tank_sieged",           OrderID::Guard, 0 },
  { "", 0, 3 },
  { "firebat",                     OrderID::Guard, 0 },
  { "", 0, 3 },
  { "medic",                       OrderID::Medic, 0 },
  { "larva",                       OrderID::ComputerAI, 3 },
  { "egg",                         OrderID::Guard, 3 },
  { "zergling",                    OrderID::Guard, 0 },
  { "hydralisk",                   OrderID::Guard, 0 },
  { "ultralisk",                   OrderID::Guard, 0 },
  { "broodling",                   OrderID::Guard, 0 },
  { "drone",                       OrderID::Guard, 3 },
  { "overlord",                    OrderID::AIPatrol, 3 },
  { "mutalisk",                    OrderID::Guard, 0 },
  { "guardian",                    OrderID::Guard, 0 },
  { "queen",                       OrderID::Guard, 0 },
  { "defiler",                     OrderID::Guard, 0 },
  { "scourge",                     OrderID::Guard, 0 },
  { "torrasque",                   OrderID::Guard, 3 },
  { "matriarch",                   OrderID::Guard, 3 },
  { "infested_terran",             OrderID::Guard, 0 },
  { "infested_kerrigan",           OrderID::Guard, 3 },
  { "unclean_one",                 OrderID::Guard, 3 },
  { "hunter_killer",               OrderID::Guard, 3 },
  { "devouring_one",               OrderID::Guard, 3 },
  { "kukulza",                     OrderID::Guard, 3 },
  { "kukulza_guardian",            OrderID::Guard, 3 },
  { "yggdrasill",                  OrderID::ComputerAI, 3 },
  { "valkyrie",                    OrderID::Guard, 0 },
  { "cocoon",                      OrderID::Guard, 3 },
  { "corsair",                     OrderID::Guard, 0 },
  { "dark_templar",                OrderID::Guard, 0 },
  { "devourer",                    OrderID::Guard, 0 },
  { "dark_archon",                 OrderID::Guard, 0 },
  { "probe",                       OrderID::Guard, 3 },
  { "zealot",                      OrderID::Guard, 0 },
  { "dragoon",                     OrderID::Guard, 0 },
  { "high_templar",                OrderID::Guard, 0 },
  { "archon",                      OrderID::Guard, 0 },
  { "shuttle",                     OrderID::PickupIdle, 0 },
  { "scout",                       OrderID::Guard, 0 },
  { "arbiter",                     OrderID::InitArbiter, 0 },
  { "carrier",                     OrderID::Carrier, 0 },
  { "interceptor",                 OrderID::Nothing, 3 },
  { "dark_templar_hero",           OrderID::Guard, 3 },
  { "zeratul",                     OrderID::Guard, 3 },
  { "tassadar_zeratul",            OrderID::Guard, 3 },
  { "fenix_zealot",                OrderID::Guard, 3 },
  { "fenix_dragoon",               OrderID::Guard, 3 },
  { "tassadar",                    OrderID::Guard, 3 },
  { "mojo",                        OrderID::Guard, 3 },
  { "warbringer",                  OrderID::Reaver, 3 },
  { "gantrithor",                  OrderID::Carrier, 3 },
  { "reaver",                      OrderID::Reaver, 0 },
  { "observer",                    OrderID::AIPatrol, 3 },
  { "scarab",                      OrderID::Nothing, 3 },
  { "danimoth",                    OrderID::InitArbiter, 3 },
  { "aldaris",                     OrderID::Guard, 3 },
  { "artanis",                     OrderID::Guard, 3 },
  { "rhynadon",                    OrderID::Guard, 3 },
  { "bengalaas",                   OrderID::Guard, 3 },
  { "", 0, 0 },
  { "", 0, 0 },
  { "scantid",                     OrderID::Guard, 3 },
  { "kakaru",                      OrderID::Guard, 3 },
  { "ragnasaur",                   OrderID::Guard, 3 },
  { "ursadon",                     OrderID::Guard, 3 },
  { "lurker_egg",                  OrderID::Guard, 3 },
  { "raszagal",                    OrderID::Guard, 0 },
  { "samir_duran",                 OrderID::Guard, 3 },
  { "alexei_stukov",               OrderID::Guard, 3 },
  { "", 0, 3 },
  { "gerard_dugalle",              OrderID::Guard, 3 },
  { "lurker",                      OrderID::Guard, 0 },
  { "infested_duran",              OrderID::Guard, 3 },
  { "", 0, 3 },
  { "command_center",              OrderID::ComputerAI, 3 },
  { "comsat_station",              OrderID::ComputerAI, 3 },
  { "nuke_silo",                   OrderID::ComputerAI, 3 },
  { "supply_depot",                OrderID::ComputerAI, 3 },
  { "refinery",                    OrderID::ComputerAI, 3 },
  { "barracks",                    OrderID::ComputerAI, 3 },
  { "academy",                     OrderID::ComputerAI, 3 },
  { "factory",                     OrderID::ComputerAI, 3 },
  { "starport",                    OrderID::ComputerAI, 3 },
  { "control_tower",               OrderID::ComputerAI, 3 },
  { "science_facility",            OrderID::ComputerAI, 3 },
  { "covert_ops",                  OrderID::ComputerAI, 3 },
  { "physics_lab",                 OrderID::ComputerAI, 3 },
  { "", 0, 3 },
  { "machine_shop",                OrderID::ComputerAI, 3 },
  { "", 0, 3 },
  { "engineering_bay",             OrderID::ComputerAI, 3 },
  { "armory",                      OrderID::ComputerAI, 3 },
  { "missile_turret",              OrderID::TowerGuard, 3 },
  { "bunker",                      OrderID::ComputerAI, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "infested_command_center",     OrderID::ComputerAI, 3 },
  { "hatchery",                    OrderID::InitCreepGrowth, 3 },
  { "lair",                        OrderID::InitCreepGrowth, 3 },
  { "hive",                        OrderID::InitCreepGrowth, 3 },
  { "nydus_canal",                 OrderID::ComputerAI, 3 },
  { "hydralisk_den",               OrderID::ComputerAI, 3 },
  { "defiler_mound",               OrderID::ComputerAI, 3 },
  { "greater_spire",               OrderID::ComputerAI, 3 },
  { "queens_nest",                 OrderID::ComputerAI, 3 },
  { "evolution_chamber",           OrderID::ComputerAI, 3 },
  { "ultralisk_cavern",            OrderID::ComputerAI, 3 },
  { "spire",                       OrderID::ComputerAI, 3 },
  { "spawning_pool",               OrderID::ComputerAI, 3 },
  { "creep_colony",                OrderID::InitCreepGrowth, 3 },
  { "spore_colony",                OrderID::InitCreepGrowth, 3 },
  { "", 0, 3 },
  { "sunken_colony",               OrderID::InitCreepGrowth, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "extractor",                   OrderID::ComputerAI, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "nexus",                       OrderID::ComputerAI, 3 },
  { "robotics_facility",           OrderID::ComputerAI, 3 },
  { "pylon",                       OrderID::InitPsiProvider, 3 },
  { "assimilator",                 OrderID::ComputerAI, 3 },
  { "", 0, 3 },
  { "observatory",                 OrderID::ComputerAI, 3 },
  { "gateway",                     OrderID::ComputerAI, 3 },
  { "", 0, 3 },
  { "photon_cannon",               OrderID::TowerGuard, 3 },
  { "citadel_of_adun",             OrderID::ComputerAI, 3 },
  { "cybernetics_core",            OrderID::ComputerAI, 3 },
  { "templar_archives",            OrderID::ComputerAI, 3 },
  { "forge",                       OrderID::ComputerAI, 3 },
  { "stargate",                    OrderID::ComputerAI, 3 },
  { "", 0, 3 },
  { "fleet_beacon",                OrderID::ComputerAI, 3 },
  { "arbiter_tribunal",            OrderID::ComputerAI, 3 },
  { "robotics_support",            OrderID::ComputerAI, 3 },
  { "shield_battery",              OrderID::ComputerAI, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "", 0, 3 },
  { "unknown", 0, 3 }

};
  
const char *pszOpcodeName[] =
{ 
  "goto",
  "notowns_jump",
  "wait",
  "start_town",
  "start_areatown",
  "expand",
  "build",
  "upgrade",
  "tech",
  "wait_build",
  "wait_buildstart",
  "attack_clear",
  "attack_add",
  "attack_prepare",
  "attack_do",
  "wait_secure",
  "capt_expand",
  "build_bunkers",
  "wait_bunkers",
  "defensebuild_gg",
  "defensebuild_ag",
  "defensebuild_ga",
  "defensebuild_aa",
  "defenseuse_gg",
  "defenseuse_ag",
  "defenseuse_ga",
  "defenseuse_aa",
  "defenseclear_gg",
  "defenseclear_ag",
  "defenseclear_ga",
  "defenseclear_aa",
  "send_suicide",
  "player_enemy",
  "player_ally",
  "default_min",
  "defaultbuild_off",
  "stop",
  "switch_rescue",
  "move_dt",
  "debug",
  "fatal_error",
  "enter_bunker",
  "value_area",
  "transports_off",
  "check_transports",
  "nuke_rate",
  "max_force",
  "clear_combatdata",
  "random_jump",
  "time_jump",
  "farms_notiming",
  "farms_timing",
  "build_turrets",
  "wait_turrets",
  "default_build",
  "harass_factor",
  "start_campaign",
  "race_jump",
  "region_size",
  "get_oldpeons",
  "groundmap_jump",
  "place_guard",
  "wait_force",
  "guard_resources",
  "call",
  "return",
  "eval_harass",
  "creep",
  "panic",
  "player_need",
  "do_morph",
  "wait_upgrades",
  "multirun",
  "rush",
  "scout_with",
  "define_max",
  "train",
  "target_expansion",
  "wait_train",
  "set_attacks",
  "set_gencmd",
  "make_patrol",
  "give_money",
  "prep_down",
  "resources_jump",
  "enter_transport",
  "exit_transport",
  "sharedvision_on",
  "sharedvision_off",
  "nuke_location",
  "harass_location",
  "implode",
  "guard_all",
  "enemyowns_jump",
  "enemyresources_jump",
  "if_dif",
  "easy_attack",
  "kill_thread",
  "killable",
  "wait_finishattack",
  "quick_attack",
  "junkyard_dog",
  "fake_nuke",
  "disruption_web",
  "recall_location",
  "set_randomseed",
  "if_owned",
  "create_nuke",
  "create_unit",
  "nuke_pos",
  "help_iftrouble",
  "allies_watch",
  "try_townpoint",
  "unknown"
};

namespace AISCRIPT
{
  const char *getOpcodeName(int iOpcode)
  {
    if ( iOpcode > LAST || iOpcode < 0 ) 
      return pszOpcodeName[LAST];
    return pszOpcodeName[iOpcode];
  }
  const char *getUnitName(int iUnitType)
  {
    int t = iUnitType;
    if ( t > BWAPI::UnitTypes::None || t < 0 )
      t = BWAPI::UnitTypes::None;
    return pszUnitInfo[t].pszScriptUnitName;
  }
 int getUnitIdleOrder(int iUnitType)
  {
    int t = iUnitType;
    if ( t > BWAPI::UnitTypes::None || t < 0 )
      t = BWAPI::UnitTypes::None;
    return pszUnitInfo[t].iComputerIdleOrder;
  }
  int getUnitInternal(int iUnitType)
  {
    int t = iUnitType;
    if ( t > BWAPI::UnitTypes::None || t < 0 )
      t = BWAPI::UnitTypes::None;
    return pszUnitInfo[t].iComputerInternal;
  }

}
