#include <string>
#include <map>
#include <set>
#include "Order.h"

namespace BWAPI2
{
  bool initializingOrder = true;
  std::string orderName[191];
  std::map<std::string, Order> orderMap;
  std::set< Order > orderSet;
  namespace Orders
  {
    BWAPI2_EXPORT const Order Die(0);
    BWAPI2_EXPORT const Order Stop(1);
    BWAPI2_EXPORT const Order Guard(2);
    BWAPI2_EXPORT const Order PlayerGuard(3);
    BWAPI2_EXPORT const Order TurretGuard(4);
    BWAPI2_EXPORT const Order BunkerGuard(5);
    BWAPI2_EXPORT const Order Move(6);
    BWAPI2_EXPORT const Order ReaverStop(7);
    BWAPI2_EXPORT const Order Attack1(8);
    BWAPI2_EXPORT const Order Attack2(9);
    BWAPI2_EXPORT const Order AttackUnit(10);
    BWAPI2_EXPORT const Order AttackFixedRange(11);
    BWAPI2_EXPORT const Order AttackTile(12);
    BWAPI2_EXPORT const Order Hover(13);
    BWAPI2_EXPORT const Order AttackMove(14);
    BWAPI2_EXPORT const Order InfestMine1(15);
    BWAPI2_EXPORT const Order Nothing1(16);
    BWAPI2_EXPORT const Order Powerup1(17);
    BWAPI2_EXPORT const Order TowerGuard(18);
    BWAPI2_EXPORT const Order TowerAttack(19);
    BWAPI2_EXPORT const Order VultureMine(20);
    BWAPI2_EXPORT const Order StayinRange(21);
    BWAPI2_EXPORT const Order TurretAttack(22);
    BWAPI2_EXPORT const Order Nothing2(23);
    BWAPI2_EXPORT const Order Nothing3(24);
    BWAPI2_EXPORT const Order DroneStartBuild(25);
    BWAPI2_EXPORT const Order DroneBuild(26);
    BWAPI2_EXPORT const Order InfestMine2(27);
    BWAPI2_EXPORT const Order InfestMine3(28);
    BWAPI2_EXPORT const Order InfestMine4(29);
    BWAPI2_EXPORT const Order BuildTerran(30);
    BWAPI2_EXPORT const Order BuildProtoss1(31);
    BWAPI2_EXPORT const Order BuildProtoss2(32);
    BWAPI2_EXPORT const Order ConstructingBuilding(33);
    BWAPI2_EXPORT const Order Repair1(34);
    BWAPI2_EXPORT const Order Repair2(35);
    BWAPI2_EXPORT const Order PlaceAddon(36);
    BWAPI2_EXPORT const Order BuildAddon(37);
    BWAPI2_EXPORT const Order Train(38);
    BWAPI2_EXPORT const Order RallyPoint1(39);
    BWAPI2_EXPORT const Order RallyPoint2(40);
    BWAPI2_EXPORT const Order ZergBirth(41);
    BWAPI2_EXPORT const Order Morph1(42);
    BWAPI2_EXPORT const Order Morph2(43);
    BWAPI2_EXPORT const Order BuildSelf1(44);
    BWAPI2_EXPORT const Order ZergBuildSelf(45);
    BWAPI2_EXPORT const Order Build5(46);
    BWAPI2_EXPORT const Order Enternyduscanal(47);
    BWAPI2_EXPORT const Order BuildSelf2(48);
    BWAPI2_EXPORT const Order Follow(49);
    BWAPI2_EXPORT const Order Carrier(50);
    BWAPI2_EXPORT const Order CarrierIgnore1(51);
    BWAPI2_EXPORT const Order CarrierStop(52);
    BWAPI2_EXPORT const Order CarrierAttack1(53);
    BWAPI2_EXPORT const Order CarrierAttack2(54);
    BWAPI2_EXPORT const Order CarrierIgnore2(55);
    BWAPI2_EXPORT const Order CarrierFight(56);
    BWAPI2_EXPORT const Order HoldPosition1(57);
    BWAPI2_EXPORT const Order Reaver(58);
    BWAPI2_EXPORT const Order ReaverAttack1(59);
    BWAPI2_EXPORT const Order ReaverAttack2(60);
    BWAPI2_EXPORT const Order ReaverFight(61);
    BWAPI2_EXPORT const Order ReaverHold(62);
    BWAPI2_EXPORT const Order TrainFighter(63);
    BWAPI2_EXPORT const Order StrafeUnit1(64);
    BWAPI2_EXPORT const Order StrafeUnit2(65);
    BWAPI2_EXPORT const Order RechargeShields1(66);
    BWAPI2_EXPORT const Order Rechargeshields2(67);
    BWAPI2_EXPORT const Order ShieldBattery(68);
    BWAPI2_EXPORT const Order Return(69);
    BWAPI2_EXPORT const Order DroneLand(70);
    BWAPI2_EXPORT const Order BuildingLand(71);
    BWAPI2_EXPORT const Order BuildingLiftoff(72);
    BWAPI2_EXPORT const Order DroneLiftoff(73);
    BWAPI2_EXPORT const Order Liftoff(74);
    BWAPI2_EXPORT const Order ResearchTech(75);
    BWAPI2_EXPORT const Order Upgrade(76);
    BWAPI2_EXPORT const Order Larva(77);
    BWAPI2_EXPORT const Order SpawningLarva(78);
    BWAPI2_EXPORT const Order Harvest1(79);
    BWAPI2_EXPORT const Order Harvest2(80);
    BWAPI2_EXPORT const Order MoveToGas(81);
    BWAPI2_EXPORT const Order WaitForGas(82);
    BWAPI2_EXPORT const Order HarvestGas(83);
    BWAPI2_EXPORT const Order ReturnGas(84);
    BWAPI2_EXPORT const Order MoveToMinerals(85);
    BWAPI2_EXPORT const Order WaitForMinerals(86);
    BWAPI2_EXPORT const Order MiningMinerals(87);
    BWAPI2_EXPORT const Order Harvest3(88);
    BWAPI2_EXPORT const Order Harvest4(89);
    BWAPI2_EXPORT const Order ReturnMinerals(90);
    BWAPI2_EXPORT const Order Harvest5(91);
    BWAPI2_EXPORT const Order EnterTransport(92);
    BWAPI2_EXPORT const Order Pickup1(93);
    BWAPI2_EXPORT const Order Pickup2(94);
    BWAPI2_EXPORT const Order Pickup3(95);
    BWAPI2_EXPORT const Order Pickup4(96);
    BWAPI2_EXPORT const Order Powerup2(97);
    BWAPI2_EXPORT const Order SiegeMode(98);
    BWAPI2_EXPORT const Order TankMode(99);
    BWAPI2_EXPORT const Order WatchTarget(100);
    BWAPI2_EXPORT const Order InitCreepGrowth(101);
    BWAPI2_EXPORT const Order SpreadCreep(102);
    BWAPI2_EXPORT const Order StoppingCreepGrowth(103);
    BWAPI2_EXPORT const Order GuardianAspect(104);
    BWAPI2_EXPORT const Order WarpingArchon(105);
    BWAPI2_EXPORT const Order CompletingArchonsummon(106);
    BWAPI2_EXPORT const Order HoldPosition2(107);
    BWAPI2_EXPORT const Order HoldPosition3(108);
    BWAPI2_EXPORT const Order Cloak(109);
    BWAPI2_EXPORT const Order Decloak(110);
    BWAPI2_EXPORT const Order Unload(111);
    BWAPI2_EXPORT const Order MoveUnload(112);
    BWAPI2_EXPORT const Order FireYamatoGun1(113);
    BWAPI2_EXPORT const Order FireYamatoGun2(114);
    BWAPI2_EXPORT const Order MagnaPulse(115);
    BWAPI2_EXPORT const Order Burrow(116);
    BWAPI2_EXPORT const Order Burrowed(117);
    BWAPI2_EXPORT const Order Unburrow(118);
    BWAPI2_EXPORT const Order DarkSwarm(119);
    BWAPI2_EXPORT const Order CastParasite(120);
    BWAPI2_EXPORT const Order SummonBroodlings(121);
    BWAPI2_EXPORT const Order EmpShockwave(122);
    BWAPI2_EXPORT const Order NukeWait(123);
    BWAPI2_EXPORT const Order NukeTrain(124);
    BWAPI2_EXPORT const Order NukeLaunch(125);
    BWAPI2_EXPORT const Order NukePaint(126);
    BWAPI2_EXPORT const Order NukeUnit(127);
    BWAPI2_EXPORT const Order NukeGround(128);
    BWAPI2_EXPORT const Order NukeTrack(129);
    BWAPI2_EXPORT const Order InitArbiter(130);
    BWAPI2_EXPORT const Order CloakNearbyUnits(131);
    BWAPI2_EXPORT const Order PlaceMine(132);
    BWAPI2_EXPORT const Order Rightclickaction(133);
    BWAPI2_EXPORT const Order SapUnit(134);
    BWAPI2_EXPORT const Order SapLocation(135);
    BWAPI2_EXPORT const Order HoldPosition4(136);
    BWAPI2_EXPORT const Order Teleport(137);
    BWAPI2_EXPORT const Order TeleporttoLocation(138);
    BWAPI2_EXPORT const Order PlaceScanner(139);
    BWAPI2_EXPORT const Order Scanner(140);
    BWAPI2_EXPORT const Order DefensiveMatrix(141);
    BWAPI2_EXPORT const Order PsiStorm(142);
    BWAPI2_EXPORT const Order Irradiate(143);
    BWAPI2_EXPORT const Order Plague(144);
    BWAPI2_EXPORT const Order Consume(145);
    BWAPI2_EXPORT const Order Ensnare(146);
    BWAPI2_EXPORT const Order StasisField(147);
    BWAPI2_EXPORT const Order Hallucination1(148);
    BWAPI2_EXPORT const Order Hallucination2(149);
    BWAPI2_EXPORT const Order ResetCollision1(150);
    BWAPI2_EXPORT const Order ResetCollision2(151);
    BWAPI2_EXPORT const Order Patrol(152);
    BWAPI2_EXPORT const Order CTFCOPInit(153);
    BWAPI2_EXPORT const Order CTFCOP1(154);
    BWAPI2_EXPORT const Order CTFCOP2(155);
    BWAPI2_EXPORT const Order ComputerAI(156);
    BWAPI2_EXPORT const Order AtkMoveEP(157);
    BWAPI2_EXPORT const Order HarassMove(158);
    BWAPI2_EXPORT const Order AIPatrol(159);
    BWAPI2_EXPORT const Order GuardPost(160);
    BWAPI2_EXPORT const Order RescuePassive(161);
    BWAPI2_EXPORT const Order Neutral(162);
    BWAPI2_EXPORT const Order ComputerReturn(163);
    BWAPI2_EXPORT const Order InitPsiProvider(164);
    BWAPI2_EXPORT const Order SelfDestrucing(165);
    BWAPI2_EXPORT const Order Critter(166);
    BWAPI2_EXPORT const Order HiddenGun(167);
    BWAPI2_EXPORT const Order OpenDoor(168);
    BWAPI2_EXPORT const Order CloseDoor(169);
    BWAPI2_EXPORT const Order HideTrap(170);
    BWAPI2_EXPORT const Order RevealTrap(171);
    BWAPI2_EXPORT const Order Enabledoodad(172);
    BWAPI2_EXPORT const Order Disabledoodad(173);
    BWAPI2_EXPORT const Order Warpin(174);
    BWAPI2_EXPORT const Order Medic(175);
    BWAPI2_EXPORT const Order MedicHeal1(176);
    BWAPI2_EXPORT const Order HealMove(177);
    BWAPI2_EXPORT const Order MedicHoldPosition(178);
    BWAPI2_EXPORT const Order MedicHeal2(179);
    BWAPI2_EXPORT const Order Restoration(180);
    BWAPI2_EXPORT const Order CastDisruptionWeb(181);
    BWAPI2_EXPORT const Order CastMindControl(182);
    BWAPI2_EXPORT const Order WarpingDarkArchon(183);
    BWAPI2_EXPORT const Order CastFeedback(184);
    BWAPI2_EXPORT const Order CastOpticalFlare(185);
    BWAPI2_EXPORT const Order CastMaelstrom(186);
    BWAPI2_EXPORT const Order JunkYardDog(187);
    BWAPI2_EXPORT const Order Fatal(188);
    BWAPI2_EXPORT const Order None(189);
    BWAPI2_EXPORT const Order Unknown(190);
    void init()
    {
      orderName[Die.getID()] = "Die";
      orderName[Stop.getID()] = "Stop";
      orderName[Guard.getID()] = "Guard";
      orderName[PlayerGuard.getID()] = "PlayerGuard";
      orderName[TurretGuard.getID()] = "TurretGuard";
      orderName[BunkerGuard.getID()] = "BunkerGuard";
      orderName[Move.getID()] = "Move";
      orderName[ReaverStop.getID()] = "ReaverStop";
      orderName[Attack1.getID()] = "Attack1";
      orderName[Attack2.getID()] = "Attack2";
      orderName[AttackUnit.getID()] = "AttackUnit";
      orderName[AttackFixedRange.getID()] = "AttackFixedRange";
      orderName[AttackTile.getID()] = "AttackTile";
      orderName[Hover.getID()] = "Hover";
      orderName[AttackMove.getID()] = "AttackMove";
      orderName[InfestMine1.getID()] = "InfestMine1";
      orderName[Nothing1.getID()] = "Nothing1";
      orderName[Powerup1.getID()] = "Powerup1";
      orderName[TowerGuard.getID()] = "TowerGuard";
      orderName[TowerAttack.getID()] = "TowerAttack";
      orderName[VultureMine.getID()] = "VultureMine";
      orderName[StayinRange.getID()] = "StayinRange";
      orderName[TurretAttack.getID()] = "TurretAttack";
      orderName[Nothing2.getID()] = "Nothing2";
      orderName[Nothing3.getID()] = "Nothing3";
      orderName[DroneStartBuild.getID()] = "DroneStartBuild";
      orderName[DroneBuild.getID()] = "DroneBuild";
      orderName[InfestMine2.getID()] = "InfestMine2";
      orderName[InfestMine3.getID()] = "InfestMine3";
      orderName[InfestMine4.getID()] = "InfestMine4";
      orderName[BuildTerran.getID()] = "BuildTerran";
      orderName[BuildProtoss1.getID()] = "BuildProtoss1";
      orderName[BuildProtoss2.getID()] = "BuildProtoss2";
      orderName[ConstructingBuilding.getID()] = "ConstructingBuilding";
      orderName[Repair1.getID()] = "Repair1";
      orderName[Repair2.getID()] = "Repair2";
      orderName[PlaceAddon.getID()] = "PlaceAddon";
      orderName[BuildAddon.getID()] = "BuildAddon";
      orderName[Train.getID()] = "Train";
      orderName[RallyPoint1.getID()] = "RallyPoint1";
      orderName[RallyPoint2.getID()] = "RallyPoint2";
      orderName[ZergBirth.getID()] = "ZergBirth";
      orderName[Morph1.getID()] = "Morph1";
      orderName[Morph2.getID()] = "Morph2";
      orderName[BuildSelf1.getID()] = "BuildSelf1";
      orderName[ZergBuildSelf.getID()] = "ZergBuildSelf";
      orderName[Build5.getID()] = "Build5";
      orderName[Enternyduscanal.getID()] = "Enternyduscanal";
      orderName[BuildSelf2.getID()] = "BuildSelf2";
      orderName[Follow.getID()] = "Follow";
      orderName[Carrier.getID()] = "Carrier";
      orderName[CarrierIgnore1.getID()] = "CarrierIgnore1";
      orderName[CarrierStop.getID()] = "CarrierStop";
      orderName[CarrierAttack1.getID()] = "CarrierAttack1";
      orderName[CarrierAttack2.getID()] = "CarrierAttack2";
      orderName[CarrierIgnore2.getID()] = "CarrierIgnore2";
      orderName[CarrierFight.getID()] = "CarrierFight";
      orderName[HoldPosition1.getID()] = "HoldPosition1";
      orderName[Reaver.getID()] = "Reaver";
      orderName[ReaverAttack1.getID()] = "ReaverAttack1";
      orderName[ReaverAttack2.getID()] = "ReaverAttack2";
      orderName[ReaverFight.getID()] = "ReaverFight";
      orderName[ReaverHold.getID()] = "ReaverHold";
      orderName[TrainFighter.getID()] = "TrainFighter";
      orderName[StrafeUnit1.getID()] = "StrafeUnit1";
      orderName[StrafeUnit2.getID()] = "StrafeUnit2";
      orderName[RechargeShields1.getID()] = "RechargeShields1";
      orderName[Rechargeshields2.getID()] = "Rechargeshields2";
      orderName[ShieldBattery.getID()] = "ShieldBattery";
      orderName[Return.getID()] = "Return";
      orderName[DroneLand.getID()] = "DroneLand";
      orderName[BuildingLand.getID()] = "BuildingLand";
      orderName[BuildingLiftoff.getID()] = "BuildingLiftoff";
      orderName[DroneLiftoff.getID()] = "DroneLiftoff";
      orderName[Liftoff.getID()] = "Liftoff";
      orderName[ResearchTech.getID()] = "ResearchTech";
      orderName[Upgrade.getID()] = "Upgrade";
      orderName[Larva.getID()] = "Larva";
      orderName[SpawningLarva.getID()] = "SpawningLarva";
      orderName[Harvest1.getID()] = "Harvest1";
      orderName[Harvest2.getID()] = "Harvest2";
      orderName[MoveToGas.getID()] = "MoveToGas";
      orderName[WaitForGas.getID()] = "WaitForGas";
      orderName[HarvestGas.getID()] = "HarvestGas";
      orderName[ReturnGas.getID()] = "ReturnGas";
      orderName[MoveToMinerals.getID()] = "MoveToMinerals";
      orderName[WaitForMinerals.getID()] = "WaitForMinerals";
      orderName[MiningMinerals.getID()] = "MiningMinerals";
      orderName[Harvest3.getID()] = "Harvest3";
      orderName[Harvest4.getID()] = "Harvest4";
      orderName[ReturnMinerals.getID()] = "ReturnMinerals";
      orderName[Harvest5.getID()] = "Harvest5";
      orderName[EnterTransport.getID()] = "EnterTransport";
      orderName[Pickup1.getID()] = "Pickup1";
      orderName[Pickup2.getID()] = "Pickup2";
      orderName[Pickup3.getID()] = "Pickup3";
      orderName[Pickup4.getID()] = "Pickup4";
      orderName[Powerup2.getID()] = "Powerup2";
      orderName[SiegeMode.getID()] = "SiegeMode";
      orderName[TankMode.getID()] = "TankMode";
      orderName[WatchTarget.getID()] = "WatchTarget";
      orderName[InitCreepGrowth.getID()] = "InitCreepGrowth";
      orderName[SpreadCreep.getID()] = "SpreadCreep";
      orderName[StoppingCreepGrowth.getID()] = "StoppingCreepGrowth";
      orderName[GuardianAspect.getID()] = "GuardianAspect";
      orderName[WarpingArchon.getID()] = "WarpingArchon";
      orderName[CompletingArchonsummon.getID()] = "CompletingArchonsummon";
      orderName[HoldPosition2.getID()] = "HoldPosition2";
      orderName[HoldPosition3.getID()] = "HoldPosition3";
      orderName[Cloak.getID()] = "Cloak";
      orderName[Decloak.getID()] = "Decloak";
      orderName[Unload.getID()] = "Unload";
      orderName[MoveUnload.getID()] = "MoveUnload";
      orderName[FireYamatoGun1.getID()] = "FireYamatoGun1";
      orderName[FireYamatoGun2.getID()] = "FireYamatoGun2";
      orderName[MagnaPulse.getID()] = "MagnaPulse";
      orderName[Burrow.getID()] = "Burrow";
      orderName[Burrowed.getID()] = "Burrowed";
      orderName[Unburrow.getID()] = "Unburrow";
      orderName[DarkSwarm.getID()] = "DarkSwarm";
      orderName[CastParasite.getID()] = "CastParasite";
      orderName[SummonBroodlings.getID()] = "SummonBroodlings";
      orderName[EmpShockwave.getID()] = "EmpShockwave";
      orderName[NukeWait.getID()] = "NukeWait";
      orderName[NukeTrain.getID()] = "NukeTrain";
      orderName[NukeLaunch.getID()] = "NukeLaunch";
      orderName[NukePaint.getID()] = "NukePaint";
      orderName[NukeUnit.getID()] = "NukeUnit";
      orderName[NukeGround.getID()] = "NukeGround";
      orderName[NukeTrack.getID()] = "NukeTrack";
      orderName[InitArbiter.getID()] = "InitArbiter";
      orderName[CloakNearbyUnits.getID()] = "CloakNearbyUnits";
      orderName[PlaceMine.getID()] = "PlaceMine";
      orderName[Rightclickaction.getID()] = "Rightclickaction";
      orderName[SapUnit.getID()] = "SapUnit";
      orderName[SapLocation.getID()] = "SapLocation";
      orderName[HoldPosition4.getID()] = "HoldPosition4";
      orderName[Teleport.getID()] = "Teleport";
      orderName[TeleporttoLocation.getID()] = "TeleporttoLocation";
      orderName[PlaceScanner.getID()] = "PlaceScanner";
      orderName[Scanner.getID()] = "Scanner";
      orderName[DefensiveMatrix.getID()] = "DefensiveMatrix";
      orderName[PsiStorm.getID()] = "PsiStorm";
      orderName[Irradiate.getID()] = "Irradiate";
      orderName[Plague.getID()] = "Plague";
      orderName[Consume.getID()] = "Consume";
      orderName[Ensnare.getID()] = "Ensnare";
      orderName[StasisField.getID()] = "StasisField";
      orderName[Hallucination1.getID()] = "Hallucination1";
      orderName[Hallucination2.getID()] = "Hallucination2";
      orderName[ResetCollision1.getID()] = "ResetCollision1";
      orderName[ResetCollision2.getID()] = "ResetCollision2";
      orderName[Patrol.getID()] = "Patrol";
      orderName[CTFCOPInit.getID()] = "CTFCOPInit";
      orderName[CTFCOP1.getID()] = "CTFCOP1";
      orderName[CTFCOP2.getID()] = "CTFCOP2";
      orderName[ComputerAI.getID()] = "ComputerAI";
      orderName[AtkMoveEP.getID()] = "AtkMoveEP";
      orderName[HarassMove.getID()] = "HarassMove";
      orderName[AIPatrol.getID()] = "AIPatrol";
      orderName[GuardPost.getID()] = "GuardPost";
      orderName[RescuePassive.getID()] = "RescuePassive";
      orderName[Neutral.getID()] = "Neutral";
      orderName[ComputerReturn.getID()] = "ComputerReturn";
      orderName[InitPsiProvider.getID()] = "InitPsiProvider";
      orderName[SelfDestrucing.getID()] = "SelfDestrucing";
      orderName[Critter.getID()] = "Critter";
      orderName[HiddenGun.getID()] = "HiddenGun";
      orderName[OpenDoor.getID()] = "OpenDoor";
      orderName[CloseDoor.getID()] = "CloseDoor";
      orderName[HideTrap.getID()] = "HideTrap";
      orderName[RevealTrap.getID()] = "RevealTrap";
      orderName[Enabledoodad.getID()] = "Enabledoodad";
      orderName[Disabledoodad.getID()] = "Disabledoodad";
      orderName[Warpin.getID()] = "Warpin";
      orderName[Medic.getID()] = "Medic";
      orderName[MedicHeal1.getID()] = "MedicHeal1";
      orderName[HealMove.getID()] = "HealMove";
      orderName[MedicHoldPosition.getID()] = "MedicHoldPosition";
      orderName[MedicHeal2.getID()] = "MedicHeal2";
      orderName[Restoration.getID()] = "Restoration";
      orderName[CastDisruptionWeb.getID()] = "CastDisruptionWeb";
      orderName[CastMindControl.getID()] = "CastMindControl";
      orderName[WarpingDarkArchon.getID()] = "WarpingDarkArchon";
      orderName[CastFeedback.getID()] = "CastFeedback";
      orderName[CastOpticalFlare.getID()] = "CastOpticalFlare";
      orderName[CastMaelstrom.getID()] = "CastMaelstrom";
      orderName[JunkYardDog.getID()] = "JunkYardDog";
      orderName[Fatal.getID()] = "Fatal";
      orderName[None.getID()] = "None";
      orderName[Unknown.getID()] = "Unknown";
      orderSet.insert(Die);
      orderSet.insert(Stop);
      orderSet.insert(Guard);
      orderSet.insert(PlayerGuard);
      orderSet.insert(TurretGuard);
      orderSet.insert(BunkerGuard);
      orderSet.insert(Move);
      orderSet.insert(ReaverStop);
      orderSet.insert(Attack1);
      orderSet.insert(Attack2);
      orderSet.insert(AttackUnit);
      orderSet.insert(AttackFixedRange);
      orderSet.insert(AttackTile);
      orderSet.insert(Hover);
      orderSet.insert(AttackMove);
      orderSet.insert(InfestMine1);
      orderSet.insert(Nothing1);
      orderSet.insert(Powerup1);
      orderSet.insert(TowerGuard);
      orderSet.insert(TowerAttack);
      orderSet.insert(VultureMine);
      orderSet.insert(StayinRange);
      orderSet.insert(TurretAttack);
      orderSet.insert(Nothing2);
      orderSet.insert(Nothing3);
      orderSet.insert(DroneStartBuild);
      orderSet.insert(DroneBuild);
      orderSet.insert(InfestMine2);
      orderSet.insert(InfestMine3);
      orderSet.insert(InfestMine4);
      orderSet.insert(BuildTerran);
      orderSet.insert(BuildProtoss1);
      orderSet.insert(BuildProtoss2);
      orderSet.insert(ConstructingBuilding);
      orderSet.insert(Repair1);
      orderSet.insert(Repair2);
      orderSet.insert(PlaceAddon);
      orderSet.insert(BuildAddon);
      orderSet.insert(Train);
      orderSet.insert(RallyPoint1);
      orderSet.insert(RallyPoint2);
      orderSet.insert(ZergBirth);
      orderSet.insert(Morph1);
      orderSet.insert(Morph2);
      orderSet.insert(BuildSelf1);
      orderSet.insert(ZergBuildSelf);
      orderSet.insert(Build5);
      orderSet.insert(Enternyduscanal);
      orderSet.insert(BuildSelf2);
      orderSet.insert(Follow);
      orderSet.insert(Carrier);
      orderSet.insert(CarrierIgnore1);
      orderSet.insert(CarrierStop);
      orderSet.insert(CarrierAttack1);
      orderSet.insert(CarrierAttack2);
      orderSet.insert(CarrierIgnore2);
      orderSet.insert(CarrierFight);
      orderSet.insert(HoldPosition1);
      orderSet.insert(Reaver);
      orderSet.insert(ReaverAttack1);
      orderSet.insert(ReaverAttack2);
      orderSet.insert(ReaverFight);
      orderSet.insert(ReaverHold);
      orderSet.insert(TrainFighter);
      orderSet.insert(StrafeUnit1);
      orderSet.insert(StrafeUnit2);
      orderSet.insert(RechargeShields1);
      orderSet.insert(Rechargeshields2);
      orderSet.insert(ShieldBattery);
      orderSet.insert(Return);
      orderSet.insert(DroneLand);
      orderSet.insert(BuildingLand);
      orderSet.insert(BuildingLiftoff);
      orderSet.insert(DroneLiftoff);
      orderSet.insert(Liftoff);
      orderSet.insert(ResearchTech);
      orderSet.insert(Upgrade);
      orderSet.insert(Larva);
      orderSet.insert(SpawningLarva);
      orderSet.insert(Harvest1);
      orderSet.insert(Harvest2);
      orderSet.insert(MoveToGas);
      orderSet.insert(WaitForGas);
      orderSet.insert(HarvestGas);
      orderSet.insert(ReturnGas);
      orderSet.insert(MoveToMinerals);
      orderSet.insert(WaitForMinerals);
      orderSet.insert(MiningMinerals);
      orderSet.insert(Harvest3);
      orderSet.insert(Harvest4);
      orderSet.insert(ReturnMinerals);
      orderSet.insert(Harvest5);
      orderSet.insert(EnterTransport);
      orderSet.insert(Pickup1);
      orderSet.insert(Pickup2);
      orderSet.insert(Pickup3);
      orderSet.insert(Pickup4);
      orderSet.insert(Powerup2);
      orderSet.insert(SiegeMode);
      orderSet.insert(TankMode);
      orderSet.insert(WatchTarget);
      orderSet.insert(InitCreepGrowth);
      orderSet.insert(SpreadCreep);
      orderSet.insert(StoppingCreepGrowth);
      orderSet.insert(GuardianAspect);
      orderSet.insert(WarpingArchon);
      orderSet.insert(CompletingArchonsummon);
      orderSet.insert(HoldPosition2);
      orderSet.insert(HoldPosition3);
      orderSet.insert(Cloak);
      orderSet.insert(Decloak);
      orderSet.insert(Unload);
      orderSet.insert(MoveUnload);
      orderSet.insert(FireYamatoGun1);
      orderSet.insert(FireYamatoGun2);
      orderSet.insert(MagnaPulse);
      orderSet.insert(Burrow);
      orderSet.insert(Burrowed);
      orderSet.insert(Unburrow);
      orderSet.insert(DarkSwarm);
      orderSet.insert(CastParasite);
      orderSet.insert(SummonBroodlings);
      orderSet.insert(EmpShockwave);
      orderSet.insert(NukeWait);
      orderSet.insert(NukeTrain);
      orderSet.insert(NukeLaunch);
      orderSet.insert(NukePaint);
      orderSet.insert(NukeUnit);
      orderSet.insert(NukeGround);
      orderSet.insert(NukeTrack);
      orderSet.insert(InitArbiter);
      orderSet.insert(CloakNearbyUnits);
      orderSet.insert(PlaceMine);
      orderSet.insert(Rightclickaction);
      orderSet.insert(SapUnit);
      orderSet.insert(SapLocation);
      orderSet.insert(HoldPosition4);
      orderSet.insert(Teleport);
      orderSet.insert(TeleporttoLocation);
      orderSet.insert(PlaceScanner);
      orderSet.insert(Scanner);
      orderSet.insert(DefensiveMatrix);
      orderSet.insert(PsiStorm);
      orderSet.insert(Irradiate);
      orderSet.insert(Plague);
      orderSet.insert(Consume);
      orderSet.insert(Ensnare);
      orderSet.insert(StasisField);
      orderSet.insert(Hallucination1);
      orderSet.insert(Hallucination2);
      orderSet.insert(ResetCollision1);
      orderSet.insert(ResetCollision2);
      orderSet.insert(Patrol);
      orderSet.insert(CTFCOPInit);
      orderSet.insert(CTFCOP1);
      orderSet.insert(CTFCOP2);
      orderSet.insert(ComputerAI);
      orderSet.insert(AtkMoveEP);
      orderSet.insert(HarassMove);
      orderSet.insert(AIPatrol);
      orderSet.insert(GuardPost);
      orderSet.insert(RescuePassive);
      orderSet.insert(Neutral);
      orderSet.insert(ComputerReturn);
      orderSet.insert(InitPsiProvider);
      orderSet.insert(SelfDestrucing);
      orderSet.insert(Critter);
      orderSet.insert(HiddenGun);
      orderSet.insert(OpenDoor);
      orderSet.insert(CloseDoor);
      orderSet.insert(HideTrap);
      orderSet.insert(RevealTrap);
      orderSet.insert(Enabledoodad);
      orderSet.insert(Disabledoodad);
      orderSet.insert(Warpin);
      orderSet.insert(Medic);
      orderSet.insert(MedicHeal1);
      orderSet.insert(HealMove);
      orderSet.insert(MedicHoldPosition);
      orderSet.insert(MedicHeal2);
      orderSet.insert(Restoration);
      orderSet.insert(CastDisruptionWeb);
      orderSet.insert(CastMindControl);
      orderSet.insert(WarpingDarkArchon);
      orderSet.insert(CastFeedback);
      orderSet.insert(CastOpticalFlare);
      orderSet.insert(CastMaelstrom);
      orderSet.insert(JunkYardDog);
      orderSet.insert(Fatal);
      orderSet.insert(None);
      orderSet.insert(Unknown);
      for(std::set<Order>::iterator i = orderSet.begin(); i != orderSet.end(); i++)
      {
        orderMap.insert(std::make_pair((*i).getName(), *i));
      }
      initializingOrder = false;
    }
  }

  Order::Order()
  {
    this->id = Orders::None.id;
  }
  Order::Order(int id)
  {
    this->id = id;
    if (!initializingOrder)
    {
      if (id < 0 || id >= 191 || orderName[id].length() == 0)
      {
        this->id = Orders::Unknown.id;
      }
    }
  }
  Order::Order(const Order& other)
  {
    this->id = other.id;
  }
  Order& Order::operator=(const Order& other)
  {
    this->id = other.id;
    return *this;
  }
  bool Order::operator==(const Order& other) const
  {
    return this->id == other.id;
  }
  bool Order::operator!=(const Order& other) const
  {
    return this->id != other.id;
  }
  bool Order::operator<(const Order& other) const
  {
    return this->id < other.id;
  }
  int Order::getID() const
  {
    return this->id;
  }
  std::string Order::getName() const
  {
    return orderName[this->id];
  }
  Order Orders::getOrder(std::string& name)
  {
    std::map<std::string, Order>::iterator i = orderMap.find(name);
    if (i == orderMap.end()) return Orders::Unknown;
    return (*i).second;
  }
  std::set<Order>& Orders::allOrders()
  {
    return orderSet;
  }
}
