#pragma once

#include "FileReader.h"
#include <windows.h>

extern DWORD g_dwHighestFrame;
void ParseActions(FileReader &fr);

namespace Actions
{
  enum Enum
  {
    Chat_Public,
    Chat_Private,
    Chat_Null,
    z__0x03,
    z__0x04,
    Keep_Alive,
    Save_Game,
    Load_Game,
    Restart_Game,
    Select_Units,
    Select_Delta_Add,
    Select_Delta_Del,
    Placebox,
    Set_Fog,
    Set_Allies,
    Set_Speed,
    Pause_On,
    Pause_Off,
    Cheat,
    Group_Units,
    Right_Click,
    Target_Click,
    z__0x16,
    z__0x17,
    Cancel_Construction,
    Cancel_Morph,
    Stop,
    Stop_Carrier,
    Stop_Reaver,
    Order_Nothing,
    Return,
    Train,
    Cancel_Train,
    Cloak_On,
    Cloak_Off,
    Unit_Morph,
    z__0x24,
    Tank_Unsiege,
    Tank_Siege,
    Build_Fighter,
    Unload_All,
    Exit_Transport,
    Summon_Archon,
    Hold_Position,
    Burrow_Down,
    Burrow_Up,
    Cancel_Nuke,
    Lift_Off,
    Research,
    Cancel_Research,
    Upgrade,
    Cancel_Upgrade,
    Cancel_Addon,
    Building_Morph,
    Stim_Pack,
    Synchro_Check,
    Voice_Off,
    Voice_On,
    Voice_Squelch,
    Voice_Enable,
    Start_Game,
    Set_Download_Progress,
    Set_Slot_Data,
    Version_Ask,
    Version_Confirm,
    Set_Race,
    Set_Force_Melee,
    Set_Force,
    Set_Slot,
    Swap_Player,
    z__0x46,
    z__0x47,
    Set_Seed,
    Request_Info,
    Set_Force_Data,
    Set_Force_Names,
    Chat_Lobby,
    Chat_Lobby_2,
    Kick_Player,
    Transfer_File,
    Response_Nothing,
    Response_Error,
    Response_Unknown,
    Response_Entered_Briefing,
    Briefing_Start,
    Set_Latency,
    Set_Replay_Speed,
    Leave_Game,
    Ping_Minimap,
    z__0x59,
    Summon_Dark_Archon,
    Set_Public_Game,
    Chat_Replay
  };
  
};
