#pragma once
#include <string>
#include <set>
namespace BWAPI
{
  class Activity
  {
    public:
      Activity();
      Activity(int id);
      Activity(const Activity& other);
      Activity& operator=(const Activity& other);
      bool operator==(const Activity& other) const;
      bool operator!=(const Activity& other) const;
      bool operator<(const Activity& other) const;
      int getID() const;
      std::string getName() const;
    private:
      int id;
  };
  // TODO: implement processor independent activity identification
  namespace Activities
  {
    Activity getActivity(std::string& name);
    std::set<Activity>& allActivities();
    void init();
    extern const Activity Die;
    extern const Activity Stop;
    extern const Activity Guard;
    extern const Activity PlayerGuard;
    extern const Activity TurretGuard;
    extern const Activity BunkerGuard;
    extern const Activity Move;
    extern const Activity ReaverStop;
    extern const Activity Attack1;
    extern const Activity Attack2;
    extern const Activity AttackUnit;
    extern const Activity AttackFixedRange;
    extern const Activity AttackTile;
    extern const Activity Hover;
    extern const Activity AttackMove;
    extern const Activity InfestMine1;
    extern const Activity Nothing1;
    extern const Activity Powerup1;
    extern const Activity TowerGuard;
    extern const Activity TowerAttack;
    extern const Activity VultureMine;
    extern const Activity StayinRange;
    extern const Activity TurretAttack;
    extern const Activity Nothing2;
    extern const Activity Nothing3;
    extern const Activity DroneStartBuild;
    extern const Activity DroneBuild;
    extern const Activity InfestMine2;
    extern const Activity InfestMine3;
    extern const Activity InfestMine4;
    extern const Activity BuildTerran;
    extern const Activity BuildProtoss1;
    extern const Activity BuildProtoss2;
    extern const Activity ConstructingBuilding;
    extern const Activity Repair1;
    extern const Activity Repair2;
    extern const Activity PlaceAddon;
    extern const Activity BuildAddon;
    extern const Activity Train;
    extern const Activity RallyPoint1;
    extern const Activity RallyPoint2;
    extern const Activity ZergBirth;
    extern const Activity Morph1;
    extern const Activity Morph2;
    extern const Activity BuildSelf1;
    extern const Activity ZergBuildSelf;
    extern const Activity Build5;
    extern const Activity Enternyduscanal;
    extern const Activity BuildSelf2;
    extern const Activity Follow;
    extern const Activity Carrier;
    extern const Activity CarrierIgnore1;
    extern const Activity CarrierStop;
    extern const Activity CarrierAttack1;
    extern const Activity CarrierAttack2;
    extern const Activity CarrierIgnore2;
    extern const Activity CarrierFight;
    extern const Activity HoldPosition1;
    extern const Activity Reaver;
    extern const Activity ReaverAttack1;
    extern const Activity ReaverAttack2;
    extern const Activity ReaverFight;
    extern const Activity ReaverHold;
    extern const Activity TrainFighter;
    extern const Activity StrafeUnit1;
    extern const Activity StrafeUnit2;
    extern const Activity RechargeShields1;
    extern const Activity Rechargeshields2;
    extern const Activity ShieldBattery;
    extern const Activity Return;
    extern const Activity DroneLand;
    extern const Activity BuildingLand;
    extern const Activity BuildingLiftoff;
    extern const Activity DroneLiftoff;
    extern const Activity Liftoff;
    extern const Activity ResearchTech;
    extern const Activity Upgrade;
    extern const Activity Larva;
    extern const Activity SpawningLarva;
    extern const Activity Harvest1;
    extern const Activity Harvest2;
    extern const Activity MoveToGas;
    extern const Activity WaitForGas;
    extern const Activity HarvestGas;
    extern const Activity ReturnGas;
    extern const Activity MoveToMinerals;
    extern const Activity WaitForMinerals;
    extern const Activity MiningMinerals;
    extern const Activity Harvest3;
    extern const Activity Harvest4;
    extern const Activity ReturnMinerals;
    extern const Activity Harvest5;
    extern const Activity EnterTransport;
    extern const Activity Pickup1;
    extern const Activity Pickup2;
    extern const Activity Pickup3;
    extern const Activity Pickup4;
    extern const Activity Powerup2;
    extern const Activity SiegeMode;
    extern const Activity TankMode;
    extern const Activity WatchTarget;
    extern const Activity InitCreepGrowth;
    extern const Activity SpreadCreep;
    extern const Activity StoppingCreepGrowth;
    extern const Activity GuardianAspect;
    extern const Activity WarpingArchon;
    extern const Activity CompletingArchonsummon;
    extern const Activity HoldPosition2;
    extern const Activity HoldPosition3;
    extern const Activity Cloak;
    extern const Activity Decloak;
    extern const Activity Unload;
    extern const Activity MoveUnload;
    extern const Activity FireYamatoGun1;
    extern const Activity FireYamatoGun2;
    extern const Activity MagnaPulse;
    extern const Activity Burrow;
    extern const Activity Burrowed;
    extern const Activity Unburrow;
    extern const Activity DarkSwarm;
    extern const Activity CastParasite;
    extern const Activity SummonBroodlings;
    extern const Activity EmpShockwave;
    extern const Activity NukeWait;
    extern const Activity NukeTrain;
    extern const Activity NukeLaunch;
    extern const Activity NukePaint;
    extern const Activity NukeUnit;
    extern const Activity NukeGround;
    extern const Activity NukeTrack;
    extern const Activity InitArbiter;
    extern const Activity CloakNearbyUnits;
    extern const Activity PlaceMine;
    extern const Activity Rightclickaction;
    extern const Activity SapUnit;
    extern const Activity SapLocation;
    extern const Activity HoldPosition4;
    extern const Activity Teleport;
    extern const Activity TeleporttoLocation;
    extern const Activity PlaceScanner;
    extern const Activity Scanner;
    extern const Activity DefensiveMatrix;
    extern const Activity PsiStorm;
    extern const Activity Irradiate;
    extern const Activity Plague;
    extern const Activity Consume;
    extern const Activity Ensnare;
    extern const Activity StasisField;
    extern const Activity Hallucination1;
    extern const Activity Hallucination2;
    extern const Activity ResetCollision1;
    extern const Activity ResetCollision2;
    extern const Activity Patrol;
    extern const Activity CTFCOPInit;
    extern const Activity CTFCOP1;
    extern const Activity CTFCOP2;
    extern const Activity ComputerAI;
    extern const Activity AtkMoveEP;
    extern const Activity HarassMove;
    extern const Activity AIPatrol;
    extern const Activity GuardPost;
    extern const Activity RescuePassive;
    extern const Activity Neutral;
    extern const Activity ComputerReturn;
    extern const Activity InitPsiProvider;
    extern const Activity SelfDestrucing;
    extern const Activity Critter;
    extern const Activity HiddenGun;
    extern const Activity OpenDoor;
    extern const Activity CloseDoor;
    extern const Activity HideTrap;
    extern const Activity RevealTrap;
    extern const Activity Enabledoodad;
    extern const Activity Disabledoodad;
    extern const Activity Warpin;
    extern const Activity Medic;
    extern const Activity MedicHeal1;
    extern const Activity HealMove;
    extern const Activity MedicHoldPosition;
    extern const Activity MedicHeal2;
    extern const Activity Restoration;
    extern const Activity CastDisruptionWeb;
    extern const Activity CastMindControl;
    extern const Activity WarpingDarkArchon;
    extern const Activity CastFeedback;
    extern const Activity CastOpticalFlare;
    extern const Activity CastMaelstrom;
    extern const Activity JunkYardDog;
    extern const Activity Fatal;
    extern const Activity None;
    extern const Activity Unknown;
  };
}
