namespace BWAPI
{
  enum MouseButton
  {
    M_LEFT   = 0,
    M_RIGHT  = 1,
    M_MIDDLE = 2,
  };
  enum Key
  {
      K_BACKSPACE   =  8,
      K_TAB         =  9,
      K_RETURN      = 13,
      K_SHIFT       = 16,
      K_CONTROL     = 17,
      K_PAUSE       = 19,
      K_ESCAPE      = 27,
      K_SPACE       = 32,
      K_PAGEUP      = 33,
      K_PAGEDOWN    = 34,
      K_END         = 35,
      K_HOME        = 36,
      K_LEFT        = 37,
      K_UP          = 38,
      K_RIGHT       = 39,
      K_DOWN        = 40,
      K_INSERT      = 45,
      K_DELETE      = 46,
      K_0           = 48,
      K_1           = 49,
      K_2           = 50,
      K_3           = 51,
      K_4           = 52,
      K_5           = 53,
      K_6           = 54,
      K_7           = 55,
      K_8           = 56,
      K_9           = 57,
      K_A           = 65,
      K_B           = 66,
      K_C           = 67,
      K_D           = 68,
      K_E           = 69,
      K_F           = 70,
      K_G           = 71,
      K_H           = 72,
      K_I           = 73,
      K_J           = 74,
      K_K           = 75,
      K_L           = 76,
      K_M           = 77,
      K_N           = 78,
      K_O           = 79,
      K_P           = 80,
      K_Q           = 81,
      K_R           = 82,
      K_S           = 83,
      K_T           = 84,
      K_U           = 85,
      K_V           = 86,
      K_W           = 87,
      K_X           = 88,
      K_Y           = 89,
      K_Z           = 90,
      K_KP0         = 96,
      K_KP1         = 97,
      K_KP2         = 98,
      K_KP3         = 99,
      K_KP4         = 100,
      K_KP5         = 101,
      K_KP6         = 102,
      K_KP7         = 103,
      K_KP8         = 104,
      K_KP9         = 105,
      K_KP_MULTIPLY = 106,
      K_KP_PLUS     = 107,
      K_KP_MINUS    = 109,
      K_KP_PERIOD   = 110,
      K_KP_DIVIDE   = 111,
      K_F1          = 112,
      K_F2          = 113,
      K_F3          = 114,
      K_F4          = 115,
      K_F5          = 116,
      K_F6          = 117,
      K_F7          = 118,
      K_F8          = 119,
      K_F9          = 120,
      K_F10         = 121,
      K_F11         = 122,
      K_F12         = 123,
  };
}