#pragma once
#include <BWAPI/Client/BulletData.h>
#include <BWAPI/Client/Client.h>
#include <BWAPI/Client/ForceData.h>
#include <BWAPI/Client/GameData.h>
#include <BWAPI/Client/PlayerData.h>
#include <BWAPI/Client/RegionData.h>
#include <BWAPI/Client/ShapeType.h>
#include <BWAPI/Client/UnitData.h>
