// TODO: automatically generate this file with CMake

#include "AIModule.cpp"
#include "AttackType.cpp"
#include "BWAPI.cpp"
#include "Color.cpp"
#include "DamageType.cpp"
#include "Error.cpp"
#include "ExplosionType.cpp"
#include "Order.cpp"
#include "PlayerType.cpp"
#include "Position.cpp"
#include "Race.cpp"
#include "TechType.cpp"
#include "TilePosition.cpp"
#include "UnitSizeType.cpp"
#include "UnitType.cpp"
#include "UpgradeType.cpp"
#include "WeaponType.cpp"
