#include <string>
#include <map>
#include <set>
#include <BWAPI/Order.h>

namespace BWAPI
{
  namespace Orders
  {
    const Order Die(0);
    const Order Stop(1);
    const Order Guard(2);
    const Order TurretGuard(3);
    const Order BunkerGuard(4);
    const Order Move(5);
    const Order ReaverStop(6);
    const Order Attack1(7);
    const Order Attack2(8);
    const Order AttackUnit(9);
    const Order AttackFixedRange(10);
    const Order AttackTile(11);
    const Order Hover(12);
    const Order AttackMove(13);
    const Order InfestMine1(14);
    const Order Nothing1(15);
    const Order Powerup1(16);
    const Order TowerGuard(17);
    const Order TowerAttack(18);
    const Order VultureMine(19);
    const Order StayinRange(20);
    const Order TurretAttack(21);
    const Order Nothing2(22);
    const Order Nothing3(23);
    const Order DroneStartBuild(24);
    const Order DroneBuild(25);
    const Order InfestMine2(26);
    const Order InfestMine3(27);
    const Order InfestMine4(28);
    const Order BuildTerran(29);
    const Order BuildProtoss1(30);
    const Order BuildProtoss2(31);
    const Order ConstructingBuilding(32);
    const Order Repair1(33);
    const Order Repair2(34);
    const Order PlaceAddon(35);
    const Order BuildAddon(36);
    const Order Train(37);
    const Order RallyPoint1(38);
    const Order RallyPoint2(39);
    const Order ZergBirth(40);
    const Order Morph1(41);
    const Order Morph2(42);
    const Order BuildSelf1(43);
    const Order ZergBuildSelf(44);
    const Order Build5(45);
    const Order Enternyduscanal(46);
    const Order BuildSelf2(47);
    const Order Follow(48);
    const Order Carrier(49);
    const Order CarrierIgnore1(50);
    const Order CarrierStop(51);
    const Order CarrierAttack1(52);
    const Order CarrierAttack2(53);
    const Order CarrierIgnore2(54);
    const Order CarrierFight(55);
    const Order HoldPosition1(56);
    const Order Reaver(57);
    const Order ReaverAttack1(58);
    const Order ReaverAttack2(59);
    const Order ReaverFight(60);
    const Order ReaverHold(61);
    const Order TrainFighter(62);
    const Order StrafeUnit1(63);
    const Order StrafeUnit2(64);
    const Order RechargeShields1(65);
    const Order Rechargeshields2(66);
    const Order ShieldBattery(67);
    const Order Return(68);
    const Order DroneLand(69);
    const Order BuildingLand(70);
    const Order BuildingLiftoff(71);
    const Order DroneLiftoff(72);
    const Order Liftoff(73);
    const Order ResearchTech(74);
    const Order Upgrade(75);
    const Order Larva(76);
    const Order SpawningLarva(77);
    const Order Harvest1(78);
    const Order Harvest2(79);
    const Order HarvestGas1(80);
    const Order HarvestGas2(81);
    const Order HarvestGas3(82);
    const Order ReturnGas(83);
    const Order MoveToMinerals(84);
    const Order HarvestMinerals2(85);
    const Order MiningMinerals(86);
    const Order Harvest3(87);
    const Order Harvest4(88);
    const Order ReturnMinerals(89);
    const Order Harvest5(90);
    const Order EnterTransport(91);
    const Order Pickup1(92);
    const Order Pickup2(93);
    const Order Pickup3(94);
    const Order Pickup4(95);
    const Order Powerup2(96);
    const Order SiegeMode(97);
    const Order TankMode(98);
    const Order WatchTarget(99);
    const Order InitCreepGrowth(100);
    const Order SpreadCreep(101);
    const Order StoppingCreepGrowth(102);
    const Order GuardianAspect(103);
    const Order WarpingArchon(104);
    const Order CompletingArchonsummon(105);
    const Order HoldPosition2(106);
    const Order HoldPosition3(107);
    const Order Cloak(108);
    const Order Decloak(109);
    const Order Unload(110);
    const Order MoveUnload(111);
    const Order FireYamatoGun1(112);
    const Order FireYamatoGun2(113);
    const Order MagnaPulse(114);
    const Order Burrow(115);
    const Order Burrowed(116);
    const Order Unburrow(117);
    const Order DarkSwarm(118);
    const Order CastParasite(119);
    const Order SummonBroodlings(120);
    const Order EmpShockwave(121);
    const Order NukeWait(122);
    const Order NukeTrain(123);
    const Order NukeLaunch(124);
    const Order NukePaint(125);
    const Order NukeUnit(126);
    const Order NukeGround(127);
    const Order NukeTrack(128);
    const Order InitArbiter(129);
    const Order CloakNearbyUnits(130);
    const Order PlaceMine(131);
    const Order Rightclickaction(132);
    const Order SapUnit(133);
    const Order SapLocation(134);
    const Order HoldPosition4(135);
    const Order Teleport(136);
    const Order TeleporttoLocation(137);
    const Order PlaceScanner(138);
    const Order Scanner(139);
    const Order DefensiveMatrix(140);
    const Order PsiStorm(141);
    const Order Irradiate(142);
    const Order Plague(143);
    const Order Consume(144);
    const Order Ensnare(145);
    const Order StasisField(146);
    const Order Hallucianation1(147);
    const Order Hallucination2(148);
    const Order ResetCollision1(149);
    const Order ResetCollision2(150);
    const Order Patrol(151);
    const Order CTFCOPInit(152);
    const Order CTFCOP1(153);
    const Order CTFCOP2(154);
    const Order ComputerAI(155);
    const Order AtkMoveEP(156);
    const Order HarassMove(157);
    const Order AIPatrol(158);
    const Order GuardPost(159);
    const Order RescuePassive(160);
    const Order Neutral(161);
    const Order ComputerReturn(162);
    const Order InitPsiProvider(163);
    const Order SelfDestrucing(164);
    const Order Critter(165);
    const Order HiddenGun(166);
    const Order OpenDoor(167);
    const Order CloseDoor(168);
    const Order HideTrap(169);
    const Order RevealTrap(170);
    const Order Enabledoodad(171);
    const Order Disabledoodad(172);
    const Order Warpin(173);
    const Order Medic(174);
    const Order MedicHeal1(175);
    const Order HealMove(176);
    const Order MedicHoldPosition(177);
    const Order MedicHeal2(178);
    const Order Restoration(179);
    const Order CastDisruptionWeb(180);
    const Order CastMindControl(181);
    const Order WarpingDarkArchon(182);
    const Order CastFeedback(183);
    const Order CastOpticalFlare(184);
    const Order CastMaelstrom(185);
    const Order JunkYardDog(186);
    const Order Fatal(187);
    const Order None(188);
    const Order Unknown(189);
  }
  std::string orderName[188];
  std::map<std::string, Order> orderMap;
  std::set< Order > orderSet;
  int orderInit()
  {
    orderName[Orders::Die.id]="Die";
    orderName[Orders::Stop.id]="Stop";
    orderName[Orders::Guard.id]="Guard";
    orderName[Orders::TurretGuard.id]="TurretGuard";
    orderName[Orders::BunkerGuard.id]="BunkerGuard";
    orderName[Orders::Move.id]="Move";
    orderName[Orders::ReaverStop.id]="ReaverStop";
    orderName[Orders::Attack1.id]="Attack1";
    orderName[Orders::Attack2.id]="Attack2";
    orderName[Orders::AttackUnit.id]="AttackUnit";
    orderName[Orders::AttackFixedRange.id]="AttackFixedRange";
    orderName[Orders::AttackTile.id]="AttackTile";
    orderName[Orders::Hover.id]="Hover";
    orderName[Orders::AttackMove.id]="AttackMove";
    orderName[Orders::InfestMine1.id]="InfestMine1";
    orderName[Orders::Nothing1.id]="Nothing1";
    orderName[Orders::Powerup1.id]="Powerup1";
    orderName[Orders::TowerGuard.id]="TowerGuard";
    orderName[Orders::TowerAttack.id]="TowerAttack";
    orderName[Orders::VultureMine.id]="VultureMine";
    orderName[Orders::StayinRange.id]="StayinRange";
    orderName[Orders::TurretAttack.id]="TurretAttack";
    orderName[Orders::Nothing2.id]="Nothing2";
    orderName[Orders::Nothing3.id]="Nothing3";
    orderName[Orders::DroneStartBuild.id]="DroneStartBuild";
    orderName[Orders::DroneBuild.id]="DroneBuild";
    orderName[Orders::InfestMine2.id]="InfestMine2";
    orderName[Orders::InfestMine3.id]="InfestMine3";
    orderName[Orders::InfestMine4.id]="InfestMine4";
    orderName[Orders::BuildTerran.id]="BuildTerran";
    orderName[Orders::BuildProtoss1.id]="BuildProtoss1";
    orderName[Orders::BuildProtoss2.id]="BuildProtoss2";
    orderName[Orders::ConstructingBuilding.id]="ConstructingBuilding";
    orderName[Orders::Repair1.id]="Repair1";
    orderName[Orders::Repair2.id]="Repair2";
    orderName[Orders::PlaceAddon.id]="PlaceAddon";
    orderName[Orders::BuildAddon.id]="BuildAddon";
    orderName[Orders::Train.id]="Train";
    orderName[Orders::RallyPoint1.id]="RallyPoint1";
    orderName[Orders::RallyPoint2.id]="RallyPoint2";
    orderName[Orders::ZergBirth.id]="ZergBirth";
    orderName[Orders::Morph1.id]="Morph1";
    orderName[Orders::Morph2.id]="Morph2";
    orderName[Orders::BuildSelf1.id]="BuildSelf1";
    orderName[Orders::ZergBuildSelf.id]="ZergBuildSelf";
    orderName[Orders::Build5.id]="Build5";
    orderName[Orders::Enternyduscanal.id]="Enternyduscanal";
    orderName[Orders::BuildSelf2.id]="BuildSelf2";
    orderName[Orders::Follow.id]="Follow";
    orderName[Orders::Carrier.id]="Carrier";
    orderName[Orders::CarrierIgnore1.id]="CarrierIgnore1";
    orderName[Orders::CarrierStop.id]="CarrierStop";
    orderName[Orders::CarrierAttack1.id]="CarrierAttack1";
    orderName[Orders::CarrierAttack2.id]="CarrierAttack2";
    orderName[Orders::CarrierIgnore2.id]="CarrierIgnore2";
    orderName[Orders::CarrierFight.id]="CarrierFight";
    orderName[Orders::HoldPosition1.id]="HoldPosition1";
    orderName[Orders::Reaver.id]="Reaver";
    orderName[Orders::ReaverAttack1.id]="ReaverAttack1";
    orderName[Orders::ReaverAttack2.id]="ReaverAttack2";
    orderName[Orders::ReaverFight.id]="ReaverFight";
    orderName[Orders::ReaverHold.id]="ReaverHold";
    orderName[Orders::TrainFighter.id]="TrainFighter";
    orderName[Orders::StrafeUnit1.id]="StrafeUnit1";
    orderName[Orders::StrafeUnit2.id]="StrafeUnit2";
    orderName[Orders::RechargeShields1.id]="RechargeShields1";
    orderName[Orders::Rechargeshields2.id]="Rechargeshields2";
    orderName[Orders::ShieldBattery.id]="ShieldBattery";
    orderName[Orders::Return.id]="Return";
    orderName[Orders::DroneLand.id]="DroneLand";
    orderName[Orders::BuildingLand.id]="BuildingLand";
    orderName[Orders::BuildingLiftoff.id]="BuildingLiftoff";
    orderName[Orders::DroneLiftoff.id]="DroneLiftoff";
    orderName[Orders::Liftoff.id]="Liftoff";
    orderName[Orders::ResearchTech.id]="ResearchTech";
    orderName[Orders::Upgrade.id]="Upgrade";
    orderName[Orders::Larva.id]="Larva";
    orderName[Orders::SpawningLarva.id]="SpawningLarva";
    orderName[Orders::Harvest1.id]="Harvest1";
    orderName[Orders::Harvest2.id]="Harvest2";
    orderName[Orders::HarvestGas1.id]="HarvestGas1";
    orderName[Orders::HarvestGas2.id]="HarvestGas2";
    orderName[Orders::HarvestGas3.id]="HarvestGas3";
    orderName[Orders::ReturnGas.id]="ReturnGas";
    orderName[Orders::MoveToMinerals.id]="MoveToMinerals";
    orderName[Orders::HarvestMinerals2.id]="HarvestMinerals2";
    orderName[Orders::MiningMinerals.id]="MiningMinerals";
    orderName[Orders::Harvest3.id]="Harvest3";
    orderName[Orders::Harvest4.id]="Harvest4";
    orderName[Orders::ReturnMinerals.id]="ReturnMinerals";
    orderName[Orders::Harvest5.id]="Harvest5";
    orderName[Orders::EnterTransport.id]="EnterTransport";
    orderName[Orders::Pickup1.id]="Pickup1";
    orderName[Orders::Pickup2.id]="Pickup2";
    orderName[Orders::Pickup3.id]="Pickup3";
    orderName[Orders::Pickup4.id]="Pickup4";
    orderName[Orders::Powerup2.id]="Powerup2";
    orderName[Orders::SiegeMode.id]="SiegeMode";
    orderName[Orders::TankMode.id]="TankMode";
    orderName[Orders::WatchTarget.id]="WatchTarget";
    orderName[Orders::InitCreepGrowth.id]="InitCreepGrowth";
    orderName[Orders::SpreadCreep.id]="SpreadCreep";
    orderName[Orders::StoppingCreepGrowth.id]="StoppingCreepGrowth";
    orderName[Orders::GuardianAspect.id]="GuardianAspect";
    orderName[Orders::WarpingArchon.id]="WarpingArchon";
    orderName[Orders::CompletingArchonsummon.id]="CompletingArchonsummon";
    orderName[Orders::HoldPosition2.id]="HoldPosition2";
    orderName[Orders::HoldPosition3.id]="HoldPosition3";
    orderName[Orders::Cloak.id]="Cloak";
    orderName[Orders::Decloak.id]="Decloak";
    orderName[Orders::Unload.id]="Unload";
    orderName[Orders::MoveUnload.id]="MoveUnload";
    orderName[Orders::FireYamatoGun1.id]="FireYamatoGun1";
    orderName[Orders::FireYamatoGun2.id]="FireYamatoGun2";
    orderName[Orders::MagnaPulse.id]="MagnaPulse";
    orderName[Orders::Burrow.id]="Burrow";
    orderName[Orders::Burrowed.id]="Burrowed";
    orderName[Orders::Unburrow.id]="Unburrow";
    orderName[Orders::DarkSwarm.id]="DarkSwarm";
    orderName[Orders::CastParasite.id]="CastParasite";
    orderName[Orders::SummonBroodlings.id]="SummonBroodlings";
    orderName[Orders::EmpShockwave.id]="EmpShockwave";
    orderName[Orders::NukeWait.id]="NukeWait";
    orderName[Orders::NukeTrain.id]="NukeTrain";
    orderName[Orders::NukeLaunch.id]="NukeLaunch";
    orderName[Orders::NukePaint.id]="NukePaint";
    orderName[Orders::NukeUnit.id]="NukeUnit";
    orderName[Orders::NukeGround.id]="NukeGround";
    orderName[Orders::NukeTrack.id]="NukeTrack";
    orderName[Orders::InitArbiter.id]="InitArbiter";
    orderName[Orders::CloakNearbyUnits.id]="CloakNearbyUnits";
    orderName[Orders::PlaceMine.id]="PlaceMine";
    orderName[Orders::Rightclickaction.id]="Rightclickaction";
    orderName[Orders::SapUnit.id]="SapUnit";
    orderName[Orders::SapLocation.id]="SapLocation";
    orderName[Orders::HoldPosition4.id]="HoldPosition4";
    orderName[Orders::Teleport.id]="Teleport";
    orderName[Orders::TeleporttoLocation.id]="TeleporttoLocation";
    orderName[Orders::PlaceScanner.id]="PlaceScanner";
    orderName[Orders::Scanner.id]="Scanner";
    orderName[Orders::DefensiveMatrix.id]="DefensiveMatrix";
    orderName[Orders::PsiStorm.id]="PsiStorm";
    orderName[Orders::Irradiate.id]="Irradiate";
    orderName[Orders::Plague.id]="Plague";
    orderName[Orders::Consume.id]="Consume";
    orderName[Orders::Ensnare.id]="Ensnare";
    orderName[Orders::StasisField.id]="StasisField";
    orderName[Orders::Hallucianation1.id]="Hallucianation1";
    orderName[Orders::Hallucination2.id]="Hallucination2";
    orderName[Orders::ResetCollision1.id]="ResetCollision1";
    orderName[Orders::ResetCollision2.id]="ResetCollision2";
    orderName[Orders::Patrol.id]="Patrol";
    orderName[Orders::CTFCOPInit.id]="CTFCOPInit";
    orderName[Orders::CTFCOP1.id]="CTFCOP1";
    orderName[Orders::CTFCOP2.id]="CTFCOP2";
    orderName[Orders::ComputerAI.id]="ComputerAI";
    orderName[Orders::AtkMoveEP.id]="AtkMoveEP";
    orderName[Orders::HarassMove.id]="HarassMove";
    orderName[Orders::AIPatrol.id]="AIPatrol";
    orderName[Orders::GuardPost.id]="GuardPost";
    orderName[Orders::RescuePassive.id]="RescuePassive";
    orderName[Orders::Neutral.id]="Neutral";
    orderName[Orders::ComputerReturn.id]="ComputerReturn";
    orderName[Orders::InitPsiProvider.id]="InitPsiProvider";
    orderName[Orders::SelfDestrucing.id]="SelfDestrucing";
    orderName[Orders::Critter.id]="Critter";
    orderName[Orders::HiddenGun.id]="HiddenGun";
    orderName[Orders::OpenDoor.id]="OpenDoor";
    orderName[Orders::CloseDoor.id]="CloseDoor";
    orderName[Orders::HideTrap.id]="HideTrap";
    orderName[Orders::RevealTrap.id]="RevealTrap";
    orderName[Orders::Enabledoodad.id]="Enabledoodad";
    orderName[Orders::Disabledoodad.id]="Disabledoodad";
    orderName[Orders::Warpin.id]="Warpin";
    orderName[Orders::Medic.id]="Medic";
    orderName[Orders::MedicHeal1.id]="MedicHeal1";
    orderName[Orders::HealMove.id]="HealMove";
    orderName[Orders::MedicHoldPosition.id]="MedicHoldPosition";
    orderName[Orders::MedicHeal2.id]="MedicHeal2";
    orderName[Orders::Restoration.id]="Restoration";
    orderName[Orders::CastDisruptionWeb.id]="CastDisruptionWeb";
    orderName[Orders::CastMindControl.id]="CastMindControl";
    orderName[Orders::WarpingDarkArchon.id]="WarpingDarkArchon";
    orderName[Orders::CastFeedback.id]="CastFeedback";
    orderName[Orders::CastOpticalFlare.id]="CastOpticalFlare";
    orderName[Orders::CastMaelstrom.id]="CastMaelstrom";
    orderName[Orders::JunkYardDog.id]="JunkYardDog";
    orderName[Orders::Fatal.id]="Fatal";
    orderName[Orders::None.id]="None";
    orderName[Orders::Unknown.id]="Unknown";

    orderSet.insert(Orders::Die);
    orderSet.insert(Orders::Stop);
    orderSet.insert(Orders::Guard);
    orderSet.insert(Orders::TurretGuard);
    orderSet.insert(Orders::BunkerGuard);
    orderSet.insert(Orders::Move);
    orderSet.insert(Orders::ReaverStop);
    orderSet.insert(Orders::Attack1);
    orderSet.insert(Orders::Attack2);
    orderSet.insert(Orders::AttackUnit);
    orderSet.insert(Orders::AttackFixedRange);
    orderSet.insert(Orders::AttackTile);
    orderSet.insert(Orders::Hover);
    orderSet.insert(Orders::AttackMove);
    orderSet.insert(Orders::InfestMine1);
    orderSet.insert(Orders::Nothing1);
    orderSet.insert(Orders::Powerup1);
    orderSet.insert(Orders::TowerGuard);
    orderSet.insert(Orders::TowerAttack);
    orderSet.insert(Orders::VultureMine);
    orderSet.insert(Orders::StayinRange);
    orderSet.insert(Orders::TurretAttack);
    orderSet.insert(Orders::Nothing2);
    orderSet.insert(Orders::Nothing3);
    orderSet.insert(Orders::DroneStartBuild);
    orderSet.insert(Orders::DroneBuild);
    orderSet.insert(Orders::InfestMine2);
    orderSet.insert(Orders::InfestMine3);
    orderSet.insert(Orders::InfestMine4);
    orderSet.insert(Orders::BuildTerran);
    orderSet.insert(Orders::BuildProtoss1);
    orderSet.insert(Orders::BuildProtoss2);
    orderSet.insert(Orders::ConstructingBuilding);
    orderSet.insert(Orders::Repair1);
    orderSet.insert(Orders::Repair2);
    orderSet.insert(Orders::PlaceAddon);
    orderSet.insert(Orders::BuildAddon);
    orderSet.insert(Orders::Train);
    orderSet.insert(Orders::RallyPoint1);
    orderSet.insert(Orders::RallyPoint2);
    orderSet.insert(Orders::ZergBirth);
    orderSet.insert(Orders::Morph1);
    orderSet.insert(Orders::Morph2);
    orderSet.insert(Orders::BuildSelf1);
    orderSet.insert(Orders::ZergBuildSelf);
    orderSet.insert(Orders::Build5);
    orderSet.insert(Orders::Enternyduscanal);
    orderSet.insert(Orders::BuildSelf2);
    orderSet.insert(Orders::Follow);
    orderSet.insert(Orders::Carrier);
    orderSet.insert(Orders::CarrierIgnore1);
    orderSet.insert(Orders::CarrierStop);
    orderSet.insert(Orders::CarrierAttack1);
    orderSet.insert(Orders::CarrierAttack2);
    orderSet.insert(Orders::CarrierIgnore2);
    orderSet.insert(Orders::CarrierFight);
    orderSet.insert(Orders::HoldPosition1);
    orderSet.insert(Orders::Reaver);
    orderSet.insert(Orders::ReaverAttack1);
    orderSet.insert(Orders::ReaverAttack2);
    orderSet.insert(Orders::ReaverFight);
    orderSet.insert(Orders::ReaverHold);
    orderSet.insert(Orders::TrainFighter);
    orderSet.insert(Orders::StrafeUnit1);
    orderSet.insert(Orders::StrafeUnit2);
    orderSet.insert(Orders::RechargeShields1);
    orderSet.insert(Orders::Rechargeshields2);
    orderSet.insert(Orders::ShieldBattery);
    orderSet.insert(Orders::Return);
    orderSet.insert(Orders::DroneLand);
    orderSet.insert(Orders::BuildingLand);
    orderSet.insert(Orders::BuildingLiftoff);
    orderSet.insert(Orders::DroneLiftoff);
    orderSet.insert(Orders::Liftoff);
    orderSet.insert(Orders::ResearchTech);
    orderSet.insert(Orders::Upgrade);
    orderSet.insert(Orders::Larva);
    orderSet.insert(Orders::SpawningLarva);
    orderSet.insert(Orders::Harvest1);
    orderSet.insert(Orders::Harvest2);
    orderSet.insert(Orders::HarvestGas1);
    orderSet.insert(Orders::HarvestGas2);
    orderSet.insert(Orders::HarvestGas3);
    orderSet.insert(Orders::ReturnGas);
    orderSet.insert(Orders::MoveToMinerals);
    orderSet.insert(Orders::HarvestMinerals2);
    orderSet.insert(Orders::MiningMinerals);
    orderSet.insert(Orders::Harvest3);
    orderSet.insert(Orders::Harvest4);
    orderSet.insert(Orders::ReturnMinerals);
    orderSet.insert(Orders::Harvest5);
    orderSet.insert(Orders::EnterTransport);
    orderSet.insert(Orders::Pickup1);
    orderSet.insert(Orders::Pickup2);
    orderSet.insert(Orders::Pickup3);
    orderSet.insert(Orders::Pickup4);
    orderSet.insert(Orders::Powerup2);
    orderSet.insert(Orders::SiegeMode);
    orderSet.insert(Orders::TankMode);
    orderSet.insert(Orders::WatchTarget);
    orderSet.insert(Orders::InitCreepGrowth);
    orderSet.insert(Orders::SpreadCreep);
    orderSet.insert(Orders::StoppingCreepGrowth);
    orderSet.insert(Orders::GuardianAspect);
    orderSet.insert(Orders::WarpingArchon);
    orderSet.insert(Orders::CompletingArchonsummon);
    orderSet.insert(Orders::HoldPosition2);
    orderSet.insert(Orders::HoldPosition3);
    orderSet.insert(Orders::Cloak);
    orderSet.insert(Orders::Decloak);
    orderSet.insert(Orders::Unload);
    orderSet.insert(Orders::MoveUnload);
    orderSet.insert(Orders::FireYamatoGun1);
    orderSet.insert(Orders::FireYamatoGun2);
    orderSet.insert(Orders::MagnaPulse);
    orderSet.insert(Orders::Burrow);
    orderSet.insert(Orders::Burrowed);
    orderSet.insert(Orders::Unburrow);
    orderSet.insert(Orders::DarkSwarm);
    orderSet.insert(Orders::CastParasite);
    orderSet.insert(Orders::SummonBroodlings);
    orderSet.insert(Orders::EmpShockwave);
    orderSet.insert(Orders::NukeWait);
    orderSet.insert(Orders::NukeTrain);
    orderSet.insert(Orders::NukeLaunch);
    orderSet.insert(Orders::NukePaint);
    orderSet.insert(Orders::NukeUnit);
    orderSet.insert(Orders::NukeGround);
    orderSet.insert(Orders::NukeTrack);
    orderSet.insert(Orders::InitArbiter);
    orderSet.insert(Orders::CloakNearbyUnits);
    orderSet.insert(Orders::PlaceMine);
    orderSet.insert(Orders::Rightclickaction);
    orderSet.insert(Orders::SapUnit);
    orderSet.insert(Orders::SapLocation);
    orderSet.insert(Orders::HoldPosition4);
    orderSet.insert(Orders::Teleport);
    orderSet.insert(Orders::TeleporttoLocation);
    orderSet.insert(Orders::PlaceScanner);
    orderSet.insert(Orders::Scanner);
    orderSet.insert(Orders::DefensiveMatrix);
    orderSet.insert(Orders::PsiStorm);
    orderSet.insert(Orders::Irradiate);
    orderSet.insert(Orders::Plague);
    orderSet.insert(Orders::Consume);
    orderSet.insert(Orders::Ensnare);
    orderSet.insert(Orders::StasisField);
    orderSet.insert(Orders::Hallucianation1);
    orderSet.insert(Orders::Hallucination2);
    orderSet.insert(Orders::ResetCollision1);
    orderSet.insert(Orders::ResetCollision2);
    orderSet.insert(Orders::Patrol);
    orderSet.insert(Orders::CTFCOPInit);
    orderSet.insert(Orders::CTFCOP1);
    orderSet.insert(Orders::CTFCOP2);
    orderSet.insert(Orders::ComputerAI);
    orderSet.insert(Orders::AtkMoveEP);
    orderSet.insert(Orders::HarassMove);
    orderSet.insert(Orders::AIPatrol);
    orderSet.insert(Orders::GuardPost);
    orderSet.insert(Orders::RescuePassive);
    orderSet.insert(Orders::Neutral);
    orderSet.insert(Orders::ComputerReturn);
    orderSet.insert(Orders::InitPsiProvider);
    orderSet.insert(Orders::SelfDestrucing);
    orderSet.insert(Orders::Critter);
    orderSet.insert(Orders::HiddenGun);
    orderSet.insert(Orders::OpenDoor);
    orderSet.insert(Orders::CloseDoor);
    orderSet.insert(Orders::HideTrap);
    orderSet.insert(Orders::RevealTrap);
    orderSet.insert(Orders::Enabledoodad);
    orderSet.insert(Orders::Disabledoodad);
    orderSet.insert(Orders::Warpin);
    orderSet.insert(Orders::Medic);
    orderSet.insert(Orders::MedicHeal1);
    orderSet.insert(Orders::HealMove);
    orderSet.insert(Orders::MedicHoldPosition);
    orderSet.insert(Orders::MedicHeal2);
    orderSet.insert(Orders::Restoration);
    orderSet.insert(Orders::CastDisruptionWeb);
    orderSet.insert(Orders::CastMindControl);
    orderSet.insert(Orders::WarpingDarkArchon);
    orderSet.insert(Orders::CastFeedback);
    orderSet.insert(Orders::CastOpticalFlare);
    orderSet.insert(Orders::CastMaelstrom);
    orderSet.insert(Orders::JunkYardDog);
    orderSet.insert(Orders::Fatal);
    orderSet.insert(Orders::None);
    orderSet.insert(Orders::Unknown);

    for(std::set<Order>::iterator i=orderSet.begin();i!=orderSet.end();i++)
    {
      orderMap.insert(std::make_pair((*i).getName(),*i));
    }
  }
  Order::Order()
  {
    this->id=Orders::None.id;
  }
  Order::Order(int id)
  {
    this->id=id;
  }
  Order::Order(const Order &other)
  {
    this->id=other.id;
  }
  Order& Order::operator=(const Order &other)
  {
    this->id=other.id;
    return *this;
  }
  bool Order::operator==(const Order &other) const
  {
    return this->id==other.id;
  }
  bool Order::operator<(const Order &other) const
  {
    return this->id<other.id;
  }
  std::string Order::getName() const
  {
    return orderName[this->id];
  }
  Order Orders::getOrder(std::string &name)
  {
    std::map<std::string, Order>::iterator i=orderMap.find(name);
    if (i==orderMap.end()) return Orders::Unknown;
    return (*i).second;
  }
  std::set<Order>& Orders::allOrders()
  {
    return orderSet;
  }
}